### PR TITLE
added choice to UsageValidityPeriod with period based on stepped dura…

### PR DESCRIPTION
**Pull request by hegedreiem**
…tion

### CODE REVIEW

**Review by seime — COMMENTED** [review]
Need xml example

**Review by syversenkr — APPROVED** [review]
Simplified example added, see https://github.com/entur/profile-examples/blob/master/netex/fares-sales/Entur-Activation-Consumption-simplified-examples.xml

**Comment by seime** [comment]
I believe the example should follow the netex repo

**Comment by syversenkr** [comment]
```
<ValidableElement id="ENT:ValidableElement:SteppedDuration" version="1">
    <validityParameterAssignments>
        <GenericParameterAssignment order="0" id="ENT:GenericParameterAssignment:1" version="1">
            <limitations>
                <UsageValidityPeriod id="ENT:UsageValidityPeriod:SteppedDuration-limitation" version="1">
                    <UsageTrigger>activation</UsageTrigger>
                    <UsageEnd>endOfFarePeriod</UsageEnd>
                    <SteppedDuration>
                        <InitialStepDuration>P1D</InitialStepDuration>
                        <SubsequentStepsDuration>P7D</SubsequentStepsDuration>
                        <StepUnit>zones</StepUnit>
                    </SteppedDuration>
                </UsageValidityPeriod>
            </limitations>
        </GenericParameterAssignment>
    </validityParameterAssignments>
</ValidableElement>
<!-- ... -->
<usageParameters>
    <UsageValidityPeriod id="ENT:UsageValidityPeriod:SteppedDuration" version="1">
        <UsageTrigger>activation</UsageTrigger>
        <UsageEnd>endOfFarePeriod</UsageEnd>
        <SteppedDuration>
            <InitialStepDuration>PT12H</InitialStepDuration>
            <SubsequentStepsDuration>PT24H</SubsequentStepsDuration>
            <StepUnit>zones</StepUnit>
        </SteppedDuration>
    </UsageValidityPeriod>
</usageParameters>
```

**Comment by seime** [comment]
Replaced by #51

**Pull request closed without merging**
